server:
  port: 8091

spring:
  application:
    name: jdbc-example
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/exampledb
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    contexts: dev
    change-log: classpath:/db/changelog/changelog-root.xml
    drop-first: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-uiyohlg5bc7ywx10.us.auth0.com/
          audience: demo-authorization-api

